version: '3.1'

services:
  client:
    build: .
    volumes:
      - "./../client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: .
    volumes:
      - "./..:/app"
    ports:
      - "8082:8082"